function gf = model10_gf(u1a,u1b,u1c,u1d,u1e,u2a,u2b,u2c,u2d,u2e,m1a,m1b,m1c,m1d,m1e,m2a,m2b,m2c,m2d,m2e)
%MODEL10_GF
%    GF = MODEL10_GF(U1A,U1B,U1C,U1D,U1E,U2A,U2B,U2C,U2D,U2E,M1A,M1B,M1C,M1D,M1E,M2A,M2B,M2C,M2D,M2E)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Apr-2022 14:35:00

gf = [m1a.*-2.0+u1a.*2.0;m1b.*-2.0+u1b.*2.0;m1c.*-2.0+u1c.*2.0;m1d.*-2.0+u1d.*2.0;m1e.*-2.0+u1e.*2.0;m2a.*-2.0+u2a.*2.0;m2b.*-2.0+u2b.*2.0;m2c.*-2.0+u2c.*2.0;m2d.*-2.0+u2d.*2.0;m2e.*-2.0+u2e.*2.0];
