function f = model10_f(u1a,u1b,u1c,u1d,u1e,u2a,u2b,u2c,u2d,u2e,m1a,m1b,m1c,m1d,m1e,m2a,m2b,m2c,m2d,m2e)
%MODEL10_F
%    F = MODEL10_F(U1A,U1B,U1C,U1D,U1E,U2A,U2B,U2C,U2D,U2E,M1A,M1B,M1C,M1D,M1E,M2A,M2B,M2C,M2D,M2E)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    13-Jul-2020 15:23:07

f = (m1a-u1a).^2+(m2a-u2a).^2+(m1b-u1b).^2+(m2b-u2b).^2+(m1c-u1c).^2+(m2c-u2c).^2+(m1d-u1d).^2+(m2d-u2d).^2+(m1e-u1e).^2+(m2e-u2e).^2;
